### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by bartos2** [glsorre/openwrt-rpi4-skywifi#1]
Ciao,
quando provo ad eseguire il comando build ricevo exit di errore. Ho testato un pi4b con ubuntu 20 come da hardware riportato.
Ho clonato il repo e il setup funziona a dovere, ma appena lancio il comando build ricevo exit di errore. Potresti aiutarmi? Vorrei sostituire il modem con un pi4.

**Comment by glsorre** [comment]
@bartos2 sarei lieto di aiutarti ma ho bisogno del log completo

PS: il repo non lo devi clonare su un pi4b con ubuntu...ti serve una macchina ubuntu 20.04 a parte...passami il log comunque sarei felice anche di refreshare il progetto

**Comment by bartos2** [comment]
Ciao @glsorre, grazie per il supporto.
Ecco il log:
`root@piwrt:~/openwrt-rpi4-skywifi#` ./build.sh
make: Entering directory '/root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64'
make[1]: Entering directory '/root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64'
make[1]: Leaving directory '/root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64'
make[1]: Entering directory '/root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64'
Generate local signing keys...
/root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64/staging_dir/host/bin/usign: line 5: /root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64/staging_dir/host/bin/../lib/ld-linux-x86-64.so.2: cannot execute binary file: Exec format error
/root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64/staging_dir/host/bin/usign: line 5: /root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64/staging_dir/host/bin/../lib/ld-linux-x86-64.so.2: Success
Cannot open file /root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64/key-build.pub
/root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64/staging_dir/host/bin/usign: line 5: /root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64/staging_dir/host/bin/../lib/ld-linux-x86-64.so.2: cannot execute binary file: Exec format error
/root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64/staging_dir/host/bin/usign: line 5: /root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64/staging_dir/host/bin/../lib/ld-linux-x86-64.so.2: Success
cp: cannot stat '/root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64/key-build.pub': No such file or directory
make[1]: *** [Makefile:222: _check_keys] Error 1
make[1]: Leaving directory '/root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64'
make: *** [Makefile:239: image] Error 2
make: Leaving directory '/root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64'
cp: cannot stat 'openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64/bin/targets/bcm27xx/bcm2711': No such file or directory
make: Entering directory '/root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64'
rm -rf /root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64/tmp /root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64/dl /root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64/build_dir/target-aarch64_cortex-a72_musl/root-bcm27xx /root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64/bin/targets/bcm27xx/bcm2711
make: Leaving directory '/root/openwrt-rpi4-skywifi/openwrt-imagebuilder-21.02.2-bcm27xx-bcm2711.Linux-x86_64'
`root@piwrt:~/openwrt-rpi4-skywifi#`

In effetti ho clonato il repo direttamente con il pi4b con ubuntu. Probabilmente l'intoppo è lì.

**Comment by glsorre** [comment]
Allora, come mi ricordavo l'immagine per il raspberry va buildata su una macchina x86-64 quindi dovresti farla su un PC con questa architettura. Se non ne hai uno con ubuntu potresti provare vagrant.

**Comment by glsorre** [comment]
@bartos2 ho aggiornato il repo, fammi sapere se riesci...la buliderei io ma non ho una macchina x86_64 disponibile al momento
